# Generated by Django 3.0.3 on 2020-10-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201006_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_post',
            field=models.ManyToManyField(default=None, related_name='liked_by', to='network.Post'),
        ),
    ]
