# Generated by Django 3.0.3 on 2020-10-08 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20201008_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
