# Generated by Django 3.0.3 on 2020-10-08 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_auto_20201008_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, default='', related_name='follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
