# Generated by Django 3.0.3 on 2020-10-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20201008_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
