# Generated by Django 3.0.3 on 2020-10-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_auto_20201010_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
