# Generated by Django 3.2.10 on 2022-01-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_remove_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
